---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frocha-oscars-redis-pvc
  labels:
    username: frocha
    env: oscars
    project: final
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
