version: '3'
services:
    web:
        build: .
        container_name: main_web_frocha
        ports:
           - 5027:5000
        volumes:
           - ./data/animals.json:/animals.json
    redis:
        image: redis:latest
        container_name: felipe-redis
        ports:
           - 6407:6379
        volumes:
           - ./config/redis.conf:/redis.conf
           - ./mydata/:/data
        command: [ "redis-server", "/redis.conf" ]
