---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frocha-test-redis-container
  labels:
    username: frocha
    env: test
    project: hw6
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi