---
apiVersion: v1
kind: Service
metadata:
  name: frocha-test-redis-service
  labels:
    username: frocha
    env: test
    project: hw6
    app: redis
spec:
  type: ClusterIP
  selector:
    project: hw6
    app: redis
  ports:
  - name: frocha-test-redis-service
    port: 6379
    targetPort: 6379