---
apiVersion: v1
kind: Service
metadata:
  name: frocha-test-flask-service
  labels:
    username: frocha
    env: test
    project: hw6
    app: flask
spec:
  type: ClusterIP
  selector:
    project: hw6
    app: flask
  ports:
  - name: frocha-test-flask-service
    port: 5000
    targetPort: 5000
