version: '3'
services:
    web:
        build: .
        container_name: web_felipe
        ports:
           - 5027:5000
        volumes:
           - ./data/filmlist.json:/filmlist.json
        user: "869469:816966"
    redis:
        image: redis:latest
        container_name: felipe-redis
        ports:
           - 6407:6379
        volumes:
           - ./config/redis.conf:/redis.conf
           - ./mydata/:/data
        command: [ "redis-server", "/redis.conf" ]
